return {
-- Table: {1}
{
   {2},
   {3},
   {4},
   {5},
   {6},
   {7},
   {8}
},
-- Table: {2}
{
    ["title"] = "0: TERMINAL AS A USER INTERFACE",
    ["headers"]={9},
    ["paragraphs"]={10}
},
-- Table: {3}
{
    ["title"] = "1: FILES",
    ["headers"]={11},
    ["paragraphs"]={12}
},
-- Table: {4}
{
    ["title"] = "2: PROCESSES",
    ["headers"]={13},
    ["paragraphs"]={14}
},
-- Table: {5}
{
    ["title"] = "3: USERS",
    ["headers"]={15},
    ["paragraphs"]={16}
},
-- Table: {6}
{
    ["title"] = "4: INFORMATION GATHERING",
    ["headers"]={17},
    ["paragraphs"]={18}
},
-- Table: {7}
{
    ["title"] = "5: ATTACKING",
    ["headers"]={19},
    ["paragraphs"]={20}
},
-- Table: {8}
{
    ["title"] = "6: TIPS AND TRICKS",
    ["headers"]={21},
    ["paragraphs"]={22}
},
-- Table: {9}
{
    "",
    "BASIC COMMANDS",
    "EXIT",
    "LOGOUT",
    "HELP",
    "MAN",
    "WHOAMI",
    "PWD",
    "COMMAND PARAMETERS",
    ""
},
-- Table: {10}
{
    "WELCOME TO THE FIRST PART OF THIS TUTORIAL! THE GAME HAS SIMILARITIES WITH A LINUX SYSTEM AND IN THIS\n" ..
    "TUTORIAL YOU WILL GET FAMILIAR WITH THE TERMINAL INTERFACE. FOR YOU THAT HAVE NEVER SEEN A TERMINAL BEFORE,\n" ..
    "IT IS A PLACE WHERE YOU ENTER TEXT-BASED COMMANDS TO CONTROL THE COMPUTER. YOU WILL LEARN ALL THE COMMANDS,\n" ..
    "WHAT THEY DO AND HOW TO USE THEM.\n" ..
    "    ARE YOU READY? LET'S BEGIN!\n",
    "EXIT - IT WILL SHUT DOWN THE GAME\n" ..
    "LOGOUT - IT WILL RETURN YOU TO THE MAIN MENU\n" ..
    "HELP - IT WILL SHOW YOU THE COMPLETE LIST OF ALL THE COMMANDS AVAILABLE\n" ..
    "MAN - BRINGS UP THIS TUTORIAL\n" ..
    "WHOAMI - PRINTS THE CURRENT USER\n" ..
    "PWD - PRINTS THE CURRENT WORKING DIRECTORY\n\n" ..
    "WE WILL START OFF WITH SOME BASIC COMMANDS. THEY SHOULD AT LEAST GET YOU GOING.\n",
    "THIS COMMAND WILL SHUT DOWN THE GAME. IT IS A CONVENIENT WAY TO END A PLAY SESSION WITHOUT HAVING TO GO\n" ..
    "THROUGH THE MAIN MENU. THE GAME WILL SAVE YOUR PROGRESS AUTOMATICALLY. YOU CAN CONTINUE YOUR PREVIOUS\n" ..
    "SESSION BY SELECTING CONTINUE FROM THE MAIN MENU.\n",
    "THIS COMMAND WILL RETURN YOU TO THE MAIN MENU. AS WITH THE 'EXIT' COMMAND, THE GAME WILL SAVE AUTOMATICALLY.\n",
    "IN THE BEGINNING THIS WILL BE AN ESSENTIAL COMMAND. IT LISTS ALL THE COMMANDS WITH A BRIEF DESCRIPTION OF\n" ..
    "WHAT THEY DO. IT CAN ALSO BE USED AS A QUICK REMINDER IF YOU HAVE FORGOTTEN A COMMAND. YOU CAN SCROLL THE\n" ..
    "HELP OUTPUT WITH THE LEFT AND RIGHT ARROW KEYS.\n",
    "STANDS FOR MANUAL AND IT WILL BRING UP THIS TUTORIAL. THIS WAY YOU CAN ALWAYS RETURN TO THE TUTORIAL.\n",
    "A NEAT LITTLE COMMAND PRINTING TO THE CONSOLE YOUR CURRENT USERNAME. IN THE GAME YOU WILL CONNECT TO OTHER\n" ..
    "COMPUTER SYSTEMS AND IT CAN BE HANDY TO KNOW WHAT YOUR CURRENT USERNAME IS. THE CURRENT USERNAME CAN ALSO\n" ..
    "BE FOUND BY CHECKING THE 'PROMPT'. THE PROMPT IS IN THE FORM OF 'USERNAME@IP-ADDRESS:WORKING DIRECTORY>'.\n",
    "SIMILAR TO 'WHOAMI' AND IT PRINTS OUT THE CURRENT WORKING DIRECTORY. WHEN CONNECTING TO A SYSTEM YOUR\n" ..
    "CURRENT WORKING DIRECTORY WILL BE '/', ALSO CALLED THE ROOT DIRECTORY. THIS INFORMATION CAN ALSO BE\n" ..
    "OBTAINED BY CHECKING THE PROMPT.\n",
    "SOME COMMANDS WILL REQUIRE ARGUMENTS OR PARAMETERS. YOU CAN PASS A COMMAND AN ARGUMENT BY SEPARATING THE\n" ..
    "COMMAND AND EACH OF THE ARGUMENTS WITH A SPACE CHARACTER ' '.\n",
    "THAT'S ALL FOR THIS PART, PLEASE FEEL FREE TO REFER BACK TO THIS TUTORIAL AT ANY TIME.\n" ..
    "SEE YOU AT THE NEXT PART OF THE TUTORIAL!"
},
-- Table: {11}
{
    "",
    "FILE COMMANDS",
    "LS",
    "CD",
    "CP",
    "MV",
    "RM",
    "MKDIR",
    "EDIT",
    "READ",
    "FILE PATHS",
    "BOOT.CFG AND SYSTEM.IMG",
    ""
},
-- Table: {12}
{
    "WELCOME BACK TO THE SECOND PART OF THIS TUTORIAL, IF YOU HAVEN'T READ THE FIRST PART I HIGHLY RECOMMEND SO.\n" ..
    "WITHOUT FURTHER ADO LET'S GET STARTED.\n",
    "LS - LIST THE FILES AND DIRECTORIES IN YOUR WORKING DIRECTORY\n" ..
    "CD - CHANGES YOUR WORKING DIRECTORY\n" ..
    "CP - COPIES A FILE OR DIRECTORY\n" ..
    "MV - MOVES A FILE OR DIRECTORY, ALSO USED FOR RENAMING\n" ..
    "RM - REMOVING A FILE OR DIRECTORY\n" ..
    "MKDIR - MAKES A DIRECTORY\n" ..
    "EDIT - OPENS A TEXT EDITOR TO EDIT A FILE\n" ..
    "READ - PRINTS THE CONTENT OF A FILE\n",
    "WHEN YOU WANT TO INSPECT THE FILES IN THE CURRENT DIRECTORY, THIS IS THE COMMAND TO USE.\n",
    "STANDS FOR CHANGE DIRECTORY. USED TO NAVIGATE THE FILESYSTEM. IT TAKES ONE PARAMETER; A FILE PATH\n" ..
    "(SEE MORE BELOW).\n",
    "STANDS FOR COPY AND IS USED TO MAKE A COPY OF A FILE AND DIRECTORY. A BACKUP IS NEVER A BAD IDEA. AS WITH\n" ..
    "'CD' IT ALSO TAKES A PATH AS AN ARGUMENT.\n",
    "STANDS FOR MOVE. IT WILL MOVE A FILE OR A DIRECTORY TO A ANOTHER PATH. BE CAREFUL WITH THIS COMMAND SINCE\n" ..
    "IT WILL OVERWRITE ANY FILE OR DIRECTORY AT THE TARGET PATH. IF NOT OBVIOUS ALREADY, IT ALSO TAKES A PATH\n" ..
    "AS AN ARGUMENT.\n",
    "STANDS FOR REMOVE AND REMOVES A FILE OR DIRECTORY. IT TAKES A PATH AS AN ARGUMENT.\n",
    "STANDS FOR MAKE DIRECTORY AND CREATES A DIRECTORY AT THE TARGET PATH. AND IT SHOULD BE NO SURPRISE THAT\n" ..
    "IT TAKES A PATH AS AN ARGUMENT.\n",
    "USE THIS COMMAND WHEN YOU WANT TO EDIT A FILE. IF THE FILE DOES NOT EXIST IT WILL CREATE IT. FILE EDITING\n" ..
    "WORKS AS YOU WOULD SUSPECT. YOU WRITE TEXT AND WHEN YOU PRESS THE ENTER/RETURN KEY THE CURSOR WILL GO TO\n" ..
    "THE NEXT LINE. THE EDITING IS APPEND ONLY, SO YOU CAN ONLY DELETE OR ADD CHARACTERS AT THE END OF THE FILE.\n" ..
    "THE COMMAND TAKES THE FILE PATH AS AN ARGUMENT.\n",
    "THE COUNTER-PART TO 'EDIT'. IT READS THE CONTENT OF A FILE AND PRINTS IT TO THE TERMINAL OUTPUT BUFFER. IT\n" ..
    "TAKES THE FILE PATH AS AN ARGUMENT.\n",
    "YOU HAVE PROBABLY WONDERED WHAT THESE PATHS LOOK LIKE. THEY WORK MUCH THE SAME WAY AS IN A UNIX ENVIRONMENT\n" ..
    "SO THEY ARE RELATIVE TO YOUR WORKING DIRECTORY. THE '..' OPERATOR WILL GO BACK ONE DIRECTORY LEVEL AND A\n" ..
    "'/' AT THE BEGINNING WILL REFER TO THE ROOT DIRECTORY. DIRECTORIES ARE SEPARATED BY THE '/' SYMBOL. TO\n" ..
    "MAKE IT CLEAR I HAVE LISTED A FEW EXAMPLES BELOW:\n" ..
    "1. /HOME/DOCUMENTS - REFERS TO THE DOCUMENTS DIRECTORY IN THE HOME DIRECTORY THAT IS IN ITSELF IN THE\n" ..
    "ROOT DIRECTORY\n" ..
    "2. PICTURES/A.TXT - REFERS TO THE FILE A.TXT IN THE PICTURES DIRECTORY IN THE CURRENT DIRECTORY\n" ..
    "3. ../B.TXT - REFERS TO THE FILE B.TXT IN THE PARENT DIRECTORY\n" ..
    "PLEASE PLAY AROUND WITH THE COMMAND 'CD' AND DIFFERENT PATHS TO MAKE YOURSELF COMFORTABLE NAVIGATING THE\n" ..
    "FILESYSTEM.\n",
    "FOR A SYSTEM TO WORK PROPERLY THERE MUST AT ALL TIMES EXIST THE 'BOOT.CFG' AND 'SYSTEM.IMG' FILES IN THE\n" ..
    "'/BOOT/' DIRECTORY. IF YOU DELETE ANY OF THE FILES THE SYSTEM WILL CRASH AND STOP THE SYSTEM FROM\n" ..
    "REBOOTING.\n" ..
    "WARNING: THIS MEANS THAT THERE IS NO WAY TO RESTORE THE SYSTEM!\n",
    "AND THAT'S ALL FOR THIS PART, SEE YOU AT THE NEXT PART OF THE TUTORIAL!"
},
-- Table: {13}
{
    "",
    "PROCESS RELATED COMMANDS",
    "PS",
    "KILL",
    "START",
    ""
},
-- Table: {14}
{
    "WELCOME BACK! IN THIS PART WE WILL TAKE A LOOK AT PROCESSES, WHAT THEY ARE AND WHAT YOU CAN DO WITH THEM.\n",
    "PS - LISTS CURRENTLY RUNNING PROCESSES\n" ..
    "KILL - KILLS A PROCESS\n" ..
    "START - STARTS A PROCESS\n",
    "STANDS FOR PROCESSES AND IS A USEFUL COMMAND FOR MONITORING THE SYSTEM. IT WILL LIST INFORMATION IN TWO\n" ..
    "COLUMNS. ON THE LEFT THE PID'S ARE LISTED. THEY ARE THE PROCESS ID'S USED IDENTIFY THE PROCESS. THE OTHER\n" ..
    "COLUMN CONTAINS THE NAMES OF THE PROCESSES.\n",
    "IT WILL KILL A PROCESS AND TAKES AS AN ARGUMENT THE PROCESS ID OF THE PROCESS TO TERMINATE. IF THE ROOT\n" ..
    "PROCESS (PID 0) IS KILLED THE SYSTEM WILL CRASH. THIS CAN BE USED AS A TACTIC.\n",
    "IT WILL START A PROCESS AND THE NEWLY CREATED PROCESS WILL BE ASSIGNED A RANDOM PID. THE COMMAND TAKES\n" ..
    "THE NAME OF THE PROCESS AS AN ARGUMENT. IT CAN BE WHATEVER YOU LIKE, BUT THERE ARE A FEW SPECIAL\n" ..
    "PROCESSES THAT WILL HAVE AN ACTUAL EFFECT ON THE SYSTEM. THOSE ARE: FIREWALL AND IDS. IF YOU START THOSE\n" ..
    "PROCESSES THEY WILL START THE FIREWALL AND THE INTRUSION DETECTION SYSTEM SERVICES AND YOU WILL BE\n" ..
    "PROTECTED. I WILL EXPLAIN THE FIREWALL AND THE IDS IN GREATER DETAIL IN LATER PARTS.\n",
    "NOW YOU HAVE LEARNED THE BASIC SYSTEM ADMINISTRATION COMMANDS. IN THE NEXT PART WE WILL TAKE A LOOK AT\n" ..
    "THE OTHER PART OF SYSTEM ADMINISTRATION, NAMELY USERS ACCOUNTS."
},
-- Table: {15}
{
    "",
    "USER ACCOUNT COMMANDS",
    "LISTUSERS",
    "ADDUSER",
    "DELUSER",
    ""
},
-- Table: {16}
{
    "WELCOME TO THE FOURTH PART IN THIS TUTORIAL. IF YOU HAVE NOT READ THE PREVIOUS PARTS PLEASE DO SO.\n" ..
    "THIS PART WILL COVER USER ACCOUNTS. HOW TO LIST THE USERS ON A SYSTEM, ADD A NEW USER ACCOUNT AND\n" ..
    "HOW TO DELETE USER ACCOUNTS.\n",
    "LISTUSERS - IT WILL LIST ALL THE USER ACCOUNTS ON A SYSTEM\n" ..
    "ADDUSER - IT WILL ADD A USER INTERACTIVELY\n" ..
    "DELUSER - IT WILL DELETE A USER\n",
    "THE COMMAND IS QUITE SELF-EXPLANATORY AND REQUIRES NO EXTRA COMMENTS\n",
    "THE COMMAND WILL ADD A NEW USER TO THE SYSTEM. THE COMMAND IS INTERACTIVE, MEANING THAT IT DOES NOT\n" ..
    "TAKE ANY ARGUMENTS, BUT ALL THE NECESSARY INFORMATION WILL BE PROMPTED FOR BY THE PROGRAM. IT WILL ASK\n" ..
    "FOR A USERNAME AND A PASSWORD FOR THE USER ACCOUNT. THEY CAN BE EMPTY, WHICH CAN PROVE TO BE USEFUL\n" ..
    "(SEE PART ABOUT ATTACKING)\n",
    "THE COMMAND WILL DELETE A USER. IT TAKES AS AN ARGUMENT THE USERNAME. IF NO ARGUMENT IS GIVEN, IT WILL\n" ..
    "TRY TO DELETE A USER WITH AN EMPTY USERNAME.\n",
    "THIS PART WAS RATHER SHORT, BUT NOW YOU SHOULD FEEL COMFORTABLE WITH THE TERMINAL AND WE CAN NOW MOVE ON\n" ..
    "TO MORE INTERESTING TOPICS LIKE ATTACKING ANOTHER SYSTEM!"
},
-- Table: {17}
{
    "",
    "INFORMATION GATHERING COMMANDS",
    "SEARCH",
    "PROBE",
    "SCAN",
    "IP ADDRESSES",
    ""
},
--Table: {18}
{
    "WELCOME BACK TO THE FIFTH PART IN THIS TUTORIAL. IN THIS PART YOU WILL LEARN TOOLS TO EXPLORE OTHER\n" ..
    "SYSTEMS AND PREPARING FOR ATTACKING THOSE SYSTEMS. I WILL QUOTE THE WAR GENERAL SUN TZU AND AUTHOR OF\n" ..
    "THE ART OF WAR:\n\n" ..
    "IF YOU KNOW YOU ENEMY AND KNOW YOURSELF, YOU NEED NOT FEAR THE RESULT OF ANY BATTLE. IF YOU KNOW\n" ..
    "YOURSELF BUT DON'T KNOW YOUR ENEMY, YOU WILL LOSE ONE BATTLE FOR EVERY VICTORY. IF YOU DON'T EVEN KNOW\n" ..
    "YOURSELF, THEN YOU WILL LOSE EVERY BATTLE.\n\n" ..
    "INFORMATION GATHERING IS THE MOST IMPORTANT STEP IN AN ATTACK. YOU CANNOT ACT WITHOUT INFORMATION. FOR\n" ..
    "THIS WE HAVE THREE COMMANDS AT OUR DISPOSAL.\n",
    "SEARCH - WILL SEARCH FOR ANY DEVICES AND SYSTEMS THAT YOU CAN ACCESS FROM YOUR CURRENT SYSTEM\n" ..
    "PROBE - WILL PROBE THE TARGET SYSTEM FOR INFORMATION\n" ..
    "SCAN - WILL SCAN THE PORTS OF THE TARGET SYSTEM\n",
    "THIS IS THE FIRST COMMAND YOU WILL USE. WITH THIS COMMAND YOU WILL FIND YOUR TARGET IP ADDRESS.\n",
    "THIS COMMAND IS USEFUL FOR GATHERING INFORMATION ABOUT THE TARGET SYSTEM'S DEFENSES. I RECOMMEND ALWAYS\n" ..
    "RUNNING THIS COMMAND BEFORE ATTACKING. THE COMMAND TAKES THE IP ADDRESS OF THE TARGET SYSTEM AS AN\n" ..
    "ARGUMENT.\n",
    "THIS COMMAND IS NECESSARY FOR FINDING OUT WHICH PORTS ARE OPEN AND CAN BE ATTACKED ON THE TARGET\n" ..
    "SYSTEM. THE COMAMND TAKES THE IP ADDRESS OF THE TARGET SYSTEM AS AN ARGUMENT.\n",
    "IP ADDRESSES ARE USED TO IDENTIFY SYSTEMS ON A NETWORK. EACH SYSTEM HAS AN IP ADDRESS AND THEY LOOK\n" ..
    "LIKE THIS: 192.168.1.2.\n",
    "ONCE YOU HAVE GATHERED ALL THE INFORMATION YOU NEED, IT IS TIME ATTACK. THAT IS THE THEME FOR THE\n" ..
    "NEXT TUTORIAL SO SEE YOU THERE!"
},
-- Table: {19}
{
    "",
    "COMMANDS",
    "HACK",
    "FIREWALL",
    "IDS",
    "POST EXPLOITATION",
    "CONNECT",
    ""
},
-- Table: {20}
{
    "WELCOME BACK! IT IS FINALLY TIME TO LEARN HOW TO ATTACK ANOTHER SYSTEM. THIS SHOULD BE EXCITING.\n",
    "HACK - ATTACK AN OPEN PORT ON A SYSTEM\n" ..
    "CONNECT - CONNECT TO A SYSTEM\n" ..
    "DISCONNECT - DISCONNECTS FROM A SYSTEM AND RETURN TO YOUR ROOT MACHINE\n",
    "THERE IS ONLY ONE COMMAND AND IT IS EASY TO USE. IT TAKES THE TARGET IP ADDRESS AND THE PORT NUMBER AS\n" ..
    "ARGUMENTS. BUT BEFORE YOU RUN IT BE SURE TO GATHER THE NECESSARY INFORMATION ABOUT THE TARGET. IT\n" ..
    "COULD PLAY A CRUCIAL ROLE.\n",
    "A SYSTEM WITH A FIREWALL WILL MAKE IT HARDER FOR YOU TO ATTACK THE SYSTEM. THE FIREWALL STRENGTH, A\n" ..
    "PERCENTAGE, IS THE RISK OF THE ATTACK FAILING. SO THE STRONGER THE FIREWALL, THE LESS CHANCE YOU HAVE\n" ..
    "OF HACKING THE SYSTEM. FOR EACH FAILED ATTEMPT TO HACK THE SYSTEM THE FIREWALL WILL STRENGTHEN BY 5%.\n",
    "THE INTRUSION DETECTION SYSTEM IS THE OTHER ESSENTIAL PART IN ANY KIND OF CYBERDEFENSE. WHEN YOU BEGIN\n" ..
    "YOUR ATTACK IT WILL START A TRACE ON YOU. IF THE DETECTION TIMER REACHES ZERO YOUR SYSTEM WILL BE\n" ..
    "COMPROMISED AND IT IS GAME OVER. DO NOT LET THAT HAPPEN! IF YOU NOTICE THAT YOU WON'T BE ABLE TO GET\n" ..
    "IN BEFORE IT TRACKS YOU, YOU CAN ABORT THE ATTACK.\n",
    "AFTER YOU HAVE GAINED ACCESS TO THE SYSTEM YOU WILL NOTICE THAT THE IDS IS STILL TRACKING YOU. THERE\n" ..
    "ARE A FEW WAYS OF DEALING WITH IT. THE FIRST, AND THE BEST OPTION IS TO KILL THE IDS PROCESS\n" ..
    "(SEE PROCESSES TUTORIAL). IF YOU DON'T HAVE TIME FOR THAT YOU CAN ALSO JUST DISCONNECT. ASSUMING YOU\n" ..
    "WANT TO HAVE PERSISTENT ACCESS TO THE SYSTEM YOU WILL HAVE TO CREATE A BACKDOOR. YOU CAN DO THIS BY\n" ..
    "ADDING A USER ACCOUNT THAT CAN LATER BE USED TO CONNECT TO THE SYSTEM. AFTER GAINING PERSISTENT ACCESS\n" ..
    "TO THE SYSTEM, REMEMBER TO RE-ENABLE THE IDS BY STARTING THE IDS PROCESS. YOU WOULD NOT WANT SOMEONE\n" ..
    "ELSE TO GAIN ACCESS TO THE SYSTEM YOU JUST HACKED.\n",
    "CONNECT IS USED TO ACCESS SYSTEMS YOU HAVE HACKED AND IT IS INTERACTIVE. IT WILL ASK FOR THE USERNAME\n" ..
    "AND PASSWORD FOR AN ACCOUNT ON THE TARGET SYSTEM. THE COMMAND TAKES THE TARGET IP ADDRESS AS AN ARGUMENT.\n",
    "CONGRATULATIONS, YOU SHOULD NOW BE ABLE TO HACK OTHER SYSTEMS. THE LAST PART OF THE TUTORIAL IS A BUNCH\n" ..
    "OF TIPS AND NEAT TRICKS YOU CAN USE. THANK YOU FOR FOLLOWING ALONG THIS TUTORIAL AND HAPPY HACKING!"
},
-- Table: {21}
{
    "",
    "NOTES",
    "COMMAND HISTORY",
    "CLEAR",
    "COLOR",
    ""
},
-- Table: {22}
{
    "WELCOME TO THE FINAL PART OF THIS TUTORIAL! I WILL SHARE SOME TIPS AND TRICKS THAT CAN HELP YOU WHEN\n" ..
    "TAKING OVER SYSTEMS.\n",
    "YOU PROBABLY NOTICED OR WILL NOTICE THE NOTES PANE ON THE RIGHT SIDE OF THE SCREEN. THIS IS THE PLACE\n" ..
    "WHERE YOU CAN STORE RELEVANT INFORMATION. YOU CAN ADD NOTES WITH THE COMMAND 'ADDNOTE' AND TAKES THE\n" ..
    "CONTENT OF THE NOTE AS ARGUMENTS. NOTICE THAT THE ARGUMENTS WILL BE PROCESSED AS ONE SINGLE ARGUMENT\n" ..
    "FOR THIS COMMAND. THIS WAY YOU NOTE CAN CONTAIN SPACE CHARACTERS. YOU CAN DELETE NOTES WITH THE COMMAND\n" ..
    "'DELNOTE'. IT TAKES THE NOTE INDEX SEEN IN THE NOTES PANE AS AN ARGUMENT. FINALLY YOU CAN USE THE\n" ..
    "COMMAND 'NOTES' TO TOGGLE THE VISIBILITY OF THE NOTES LIST.\n\n" ..
    "NOTES CAN BE A POWERFUL TOOL TO HELP YOU WITH INFORMATION GATHERING. YOU CAN STORE IP ADDRESSES AND\n" ..
    "FIREWALL/IDS INFORMATION THERE.\n",
    "AS YOU EXECUTE COMMANDS THE TERMINAL WILL STORE THE LAST 10 COMMANDS IN A COMMAND HISTORY. THIS WAY\n" ..
    "YOU CAN ACCESS YOUR RECENTLY EXECUTED COMMANDS BY PRESSING THE UP AND DOWN ARROW KEYS.\n",
    "IF YOU FOR SOME REASON WANT TO CLEAR THE OUTPUT BUFFER OF THE TERMINAL YOU CAN USE THIS COMMAND.\n",
    "YOU MIGHT HAVE NOTICED THAT EACH SYSTEM HAS SOME COLORED ASSIGNED TO IT. THIS CAN BE CHANGED WITH THE\n" ..
    "COLOR COMMAND. WITHOUT ANY ARGUMENTS THE COMMAND PRINTS OUT THE CURRENT COLOR CONFIGURATION (RGB VALUES).\n" ..
    "IF YOU WANT TO CHANGE THE CURRENT COLOR YOU PROVIDE THE COMMAND WITH THE THREE R, G, B VALUES. THEY\n" ..
    "RANGE FROM 0 TO 255.\n",
    "AND THAT IS IT! YOU ARE NOW READY TO EXPLORE THE WORLD. BE ON THE LOOKOUT FOR EASTER EGGS AND SECRETS\n" ..
    "AROUND THE FILESYSTEMS OF THE SYSTEMS YOU HACK. I THANK YOU FOR READING THIS TUTORIAL AND WISH YOU THE\n" ..
    "BEST OF LUCK.\n\n" ..
    "~ DOC"
}
}
